import React from 'react'

export default function About(props) {
    return (
        <div>
            <h2>About {props.match.params.id} and {props.match.params.name}</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque in nobis tenetur minus nemo temporibus aut consequuntur fuga dicta, vel sed! Eos, accusantium voluptate! Soluta porro nobis beatae minus magnam.
                Velit inventore esse voluptate suscipit earum culpa eius rem? Deserunt quidem delectus quam eaque voluptatum hic vel tempore eligendi commodi. Numquam amet minus incidunt sapiente nostrum sequi fugiat earum dolores!
                Incidunt molestiae quia quis pariatur natus tenetur cum quasi ipsa repudiandae repellendus culpa, laudantium, iure eum. Modi deleniti, nostrum provident iure, mollitia exercitationem non dicta aliquam ullam expedita autem harum?
                Rerum odit, quas magnam facilis esse eligendi modi iusto ipsam quidem! Laboriosam, repudiandae ea cum voluptatum nam impedit nesciunt obcaecati natus dolor non excepturi, magni voluptate iusto. Ex, eveniet temporibus?
                Earum nisi quasi deleniti ea repudiandae rem sit at quis autem consectetur quidem nemo voluptate reprehenderit error placeat cumque neque ipsa, dignissimos fugit iure perspiciatis distinctio vel quaerat. Accusamus, nam.
                Illum molestias beatae tempora amet ipsum voluptatem maxime optio reiciendis quia, numquam autem, tempore fugiat temporibus facilis sint rem quaerat qui? A veritatis natus eaque enim! Eaque nihil ab qui.
                Nam vitae a recusandae error fuga consequuntur atque mollitia nobis totam deserunt, accusamus aliquid tempora veritatis itaque corporis laborum illum officia earum ratione reprehenderit et? Non eligendi placeat porro voluptas?
                Veniam magnam numquam explicabo sint quasi optio, doloremque totam corporis eligendi dignissimos ducimus, neque nobis suscipit, nam reiciendis rem facilis est? Ut facere, necessitatibus aspernatur doloribus sed modi earum debitis.
                Dolorem debitis voluptatum nisi delectus accusantium obcaecati consectetur laudantium soluta. Ratione quo eveniet quam vero voluptatum, maiores pariatur aliquam suscipit, laborum exercitationem ducimus labore eius, expedita corrupti consequatur aut. Esse.
                Sequi, dolorum a error rerum iusto odit, atque repellendus magni non eos quia veritatis officia voluptates aut laudantium deserunt, numquam eveniet ullam sed consequatur reprehenderit consectetur aliquid fuga! Ipsam, doloribus.
                Dolorem odio maiores inventore iusto neque asperiores. Explicabo odio nam repellat, similique velit tempora reiciendis eligendi culpa quos iusto beatae vel repellendus rem facere optio sequi! Natus odit sit at.
                Asperiores dolores necessitatibus quae voluptatem nisi nobis quo saepe totam est placeat et quisquam fuga ratione sit, eveniet, nihil in delectus atque illum aliquam? Eius ex cupiditate nihil hic ad.
                Dolores delectus, quibusdam deserunt ducimus repellendus natus ipsam nulla illo laborum a. Aliquid delectus similique eum doloremque, consectetur et quae sint quis velit! Molestiae quo consequatur iste minima nisi quam.
                Officia deserunt asperiores est soluta! Quod voluptatibus voluptatum iure officia dolores tempora eos esse suscipit reprehenderit eveniet illo, quibusdam, hic reiciendis harum consequatur, qui fugit aliquid dolor ex iste quasi.
                Quis officia autem est doloremque sapiente ullam numquam magni sed iste. Nulla deleniti, ut laboriosam, praesentium maiores ex fugit ratione quos repudiandae ducimus dignissimos ad alias dolor tenetur eos culpa.
                Dicta ipsa iste ipsam deleniti? Quia perspiciatis fugiat consequatur tempore aperiam commodi ipsa ipsum pariatur nulla? Sint aperiam odio illum praesentium libero, non reprehenderit, soluta pariatur illo nesciunt voluptatibus accusantium.
                Iusto, sequi. Placeat fugiat architecto repudiandae magni, reiciendis vel earum corporis quam optio unde dolores, tenetur tempore dolore nihil! Voluptas in modi odio dolorem facere vitae aliquid laborum unde quia.
                Animi nisi voluptatum, aliquid illo ipsum sint, iure nesciunt voluptas perferendis atque quis minima magnam voluptates aperiam maiores veniam? Recusandae laudantium, ex eligendi veritatis accusantium natus eum optio fuga quisquam.
                Aperiam error ea consectetur adipisci, numquam similique omnis commodi. A exercitationem nam recusandae, deleniti, nisi placeat veritatis ipsa ipsum magni quibusdam sapiente magnam. Exercitationem quasi quae voluptas, blanditiis eum accusamus!
                Nisi error aliquam dolore minus veritatis quo dolorum doloribus sequi, commodi illum quasi atque? Dolorum eum ipsum molestias ut! Suscipit, ducimus mollitia odio ipsum repellendus nobis cumque eligendi maiores? Vitae.
                Dolorum, adipisci aspernatur aliquid amet quisquam recusandae, animi possimus aut atque cumque hic quos mollitia nam voluptatibus sunt voluptas quas illo ex consequuntur rerum? Praesentium perferendis inventore incidunt accusamus? Repellendus!
                Recusandae esse animi reprehenderit autem veritatis quasi debitis accusamus, architecto nam maxime commodi nostrum itaque dolorem quia labore quis? Numquam ratione nostrum quam itaque vel obcaecati voluptas beatae, accusantium nemo!
                Fugit beatae deleniti distinctio quas aliquid praesentium fugiat minima vel, deserunt perferendis architecto dolorum incidunt iusto nesciunt libero doloremque, laboriosam cumque accusamus ea odio, nemo quae! Consequatur repellendus laboriosam nesciunt.
                Vitae numquam molestias esse quidem, alias fugit soluta reprehenderit optio nam, iure nostrum veniam voluptas amet asperiores, atque quae error aperiam. Enim, porro. Facere ratione maxime aspernatur maiores veniam voluptatibus.
                Deleniti repudiandae quaerat voluptatum rem, quos ratione veniam maiores aliquid maxime tempora accusantium dolores molestias temporibus, similique delectus officiis voluptate sunt porro, architecto sed dolore at qui expedita. Deserunt, nisi.
                Esse, iusto temporibus cum qui maxime neque labore perspiciatis facere voluptate omnis debitis placeat magnam beatae assumenda laboriosam animi deserunt? Adipisci tenetur quod ad odio obcaecati. Labore ipsum cum illo?
                Nobis doloremque atque temporibus, velit maxime ipsa reprehenderit exercitationem mollitia vitae placeat sunt id? Quibusdam esse accusamus vero illo deleniti aspernatur magnam saepe facere corporis eaque! Dolorum quo illo placeat.
                Earum, mollitia consequuntur ad vel distinctio quidem repudiandae officia quisquam alias provident aliquid molestiae, delectus optio recusandae, assumenda aut veniam accusantium tempore minima quia labore! Eius, consequatur? Praesentium, possimus deleniti.
                Aspernatur corporis ipsa officiis debitis, sint, eius recusandae modi nobis culpa fugit provident id optio itaque tempora! Odit consectetur magnam error. Eos aspernatur velit omnis? Ducimus fugit quia expedita tempore?
                Voluptates molestiae, doloribus nihil libero officiis, dolores repudiandae ducimus hic magnam eveniet saepe deleniti deserunt rem fugiat eligendi minus magni natus nam. Maxime beatae architecto, vel quaerat at error. Ipsam.
                Fugiat illum reprehenderit laborum eum, autem non, doloremque ipsam expedita, doloribus et quae ut dolore eaque est at ducimus fugit assumenda. Ratione accusantium iusto dignissimos perferendis dolor consequatur, adipisci incidunt.
                Tempora assumenda ipsa similique nisi veritatis optio esse nulla mollitia velit nostrum animi libero perferendis molestiae consequuntur magni magnam numquam deleniti expedita, recusandae, quasi inventore obcaecati. Ab dolorem ipsam perspiciatis.
                Consequatur laboriosam maiores aliquam hic tempore dolorum sunt, a perspiciatis cum dolore eos consectetur sint quaerat reiciendis doloribus incidunt praesentium illum. Dolore velit aut sit, animi minima consectetur deserunt asperiores.
                Debitis autem fugit quo, sit porro architecto possimus quod necessitatibus laboriosam numquam commodi modi in quam iusto? Cumque, quod nulla? Explicabo, dolores! Modi aspernatur voluptates hic iusto eligendi cupiditate itaque?
                Neque rem dicta aliquam temporibus nisi velit. Corporis aliquid laudantium deleniti at commodi beatae tenetur molestias voluptates, labore minima rem illum eveniet! Obcaecati non, repellendus perferendis totam ipsam dolorem. Tempora?
                Ullam vero, ea deleniti veritatis consequuntur accusamus perspiciatis dolorem architecto, voluptas a praesentium debitis itaque tempore eum porro incidunt sint. Aut rerum sequi eos molestiae nemo placeat adipisci ullam tenetur.
                Molestiae laborum reiciendis voluptatum vitae eveniet quis? Doloremque labore velit officia nostrum odit adipisci iste vel, culpa fuga iure hic expedita temporibus? Nulla autem, harum reiciendis molestiae iusto veniam suscipit!
                Magnam necessitatibus sapiente nesciunt eveniet facilis sed cum beatae blanditiis animi repellendus error voluptatum earum, omnis neque veniam ipsum quisquam odio impedit explicabo expedita tempore. Quod quisquam ipsum quaerat sit.
                Distinctio officiis, repudiandae quasi dolores labore veritatis atque nobis obcaecati animi aut, saepe exercitationem repellendus facilis autem, rem unde. Aspernatur vero pariatur soluta quia ad tempora placeat odio velit quos?
                Similique ad sunt iusto iste sed cupiditate, veniam optio, eos repellat vel harum modi quas ipsa culpa reprehenderit, atque dignissimos ullam dicta! Tempora eos veritatis facere doloribus. Asperiores, modi ea!
                Iure placeat et at maiores incidunt sequi blanditiis neque magni vitae molestiae autem quam, non voluptas porro ullam esse, labore fuga consequatur culpa ad veritatis eveniet ducimus. Itaque, recusandae nostrum!
                Consequatur obcaecati ipsam incidunt. Esse vero dignissimos officia quisquam sed exercitationem consectetur amet inventore numquam, perspiciatis, reprehenderit tempore facere est, quis dolores cupiditate neque magnam atque ducimus perferendis maiores aspernatur.
                Inventore magni odit aut vitae dolor eligendi a numquam? Aperiam ipsam nam labore eius. Optio accusamus suscipit vitae corporis at earum porro iure adipisci, cum molestiae, quisquam distinctio, unde non?
                Dolor corrupti sint dignissimos consectetur iste placeat nemo cum eius deleniti vitae quisquam quas suscipit ipsa soluta culpa cumque repellat corporis odio facilis atque, quos veritatis molestias eligendi blanditiis. Dicta.
                Odit, veniam perferendis! Fugiat in fuga ullam sequi ducimus eum est ad, molestias error sint ipsa laboriosam aut illum sapiente, quia velit quisquam laborum nulla debitis cupiditate recusandae minus quibusdam?
                Voluptatibus sint totam cumque odit asperiores! Sequi ad distinctio, architecto laboriosam officiis odio! Quae ad, aperiam esse consequuntur maiores sit saepe molestiae illo nihil suscipit pariatur dolorem nesciunt doloremque optio.
                Impedit id beatae autem dolores et totam assumenda ipsam nobis, ea accusamus deserunt voluptate obcaecati dignissimos reprehenderit amet? Accusamus aut blanditiis ut temporibus neque nobis, nisi recusandae fugit eius quasi.
                Magni dolore hic doloremque veniam, obcaecati expedita nemo quis distinctio, porro earum sit natus quod debitis nam perspiciatis cumque dolorum tenetur veritatis nisi eligendi harum aperiam commodi est. Voluptatibus, magni?
                Voluptates ex blanditiis repellendus porro provident laudantium debitis dolorum consectetur inventore obcaecati ducimus quas voluptate eaque, nam facere voluptatem cum sequi natus numquam saepe asperiores! Autem velit magnam repellendus quae.
                Consectetur error similique perferendis suscipit natus quibusdam quam deserunt corrupti rem itaque corporis quos eos recusandae tenetur dolorem officia, provident minima aliquid ab et. Tenetur veritatis enim inventore debitis ratione.
            </p>
        </div>
    )
}
